language: node_js
sudo: false
branches:
  only:
    - master
node_js:
  - "8"
  - "10"
  - "12"
cache: yarn
install:
  - npm install
before_script:
  # Building sources
  - npm run build
script:
  - npm run lint
