routes:

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: tag:-en
  /en/:
    permalink: /en/{slug}/
    template: index
    filter: tag:en

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
